### ISSUE TITLE
Problem with import computers.json

### ISSUE THREAD

**Issue by enj5oy** [fortalice/bofhound#8]
I use pyldapsearch with filter Objectclass=computers.
neo4j community version 4.3.13
Then i run bofhound output is computers.json file.
I open Bloodhound 4.1.0 release is Feb 10 2022
I can not upload computers.json file to bloodhound
![issue](https://github.com/fortalice/bofhound/assets/143943083/321527c5-9b78-4929-8990-dee572e5cf6c)

**Comment by Tw1sm** [comment]
@enj5oy could you open this issue over [here](https://github.com/coffeegist/bofhound)? We are in the process of migrating bofhound maintenance and development to that fork

**Comment by enj5oy** [comment]
@Tw1sm In fork i can not create issue.

**Comment by Tw1sm** [comment]
@enj5oy apologies, you should be able to now!

**Comment by Hexix23** [comment]
@enj5oy Were you finally able to fix the error with the computer.json?

I am having the problem, if it is possible to access what version of neo4j, bloodhound are you using it would help a lot. 
Thanks
